### ISSUE TITLE
Vivliostyle formatter fails on w3c specs

### ISSUE THREAD

**Issue by skoji** [vivliostyle/vivliostyle-formatter-issues#11]
**Note:** this issue was imported, but it was originally created by [frivoal](https://github.com/frivoal)...

**Version:**
Beta

**Step to reproduce:**
run 
``` 
path/to/vivliostyle-formatter http://www.w3.org/TR/selectors4/
```
or alternatively, run
```
wget -p http://www.w3.org/TR/selectors4/ && path/to/vivliostyle-formatter www.w3.org/TR/selectors4/index.html
```

**Result:**
A pdf file containing the following error message is generated:
> This page contains the following errors:
> error on line 4 at column 11: AttValue: " or ' expected
> Below is a rendering of the page up to the first error.

**Expected result:**
I expect the same file to be produced as with the following steps:
1) Open http://www.w3.org/TR/selectors4/index.html in firefox
2) Under the "File" menu, chose "Save page as..."
3) In the saving dialog, chose "Format: Web page, complete", and save
4) run
```
path/to/vivliostyle-formatter "Selectors Level 4.html"
```

**Comment by skoji** [comment]
The difference between wget and Firefox save page : 

wget : `<html lang=en>`
Firefox : `<html lang="en">`

This is the direct cause of this bug. I am not yet able to figure out why this occurs only in formatter, not in vivliostyle chrome extension.

**Comment by skoji** [comment]
**Note:** this comment was imported, but it was originally made by [kwkbtr](https://github.com/kwkbtr)...

It might be somewhat related to this issue: vivliostyle/vivliostyle.js#65
Current Vivliostyle.js does not handle Content-Type correctly.

**Comment by skoji** [comment]
**Note:** this comment was imported, but it was originally made by [kwkbtr](https://github.com/kwkbtr)...

Fix on Vivliostyle.js (vivliostyle/vivliostyle.js#73) resolves this issue.
(I updated Vivliostyle.js in Formatter and confirmed locally)

**Comment by kwkbtr** [comment]
Supported in VersaType Converter 2.0.
